### ISSUE TITLE
简单优化

### ISSUE THREAD

**Issue by DragonYH** [Erohal/Yooc-Auto-Exam-Bot#1]
程序在运行完成后直接退出，输出的填空答案无法体现
最后添加input （）以作为停留

另外谢谢大佬，懒狗的胜利！！！！

**Comment by Erohal** [comment]
由于填空题questionid无法直接获得，只得以输出答案再由人工填入，但是本人发现，questionid可以间接获得，或许程序可以完成填空题自动化操作了，现在的解决方案就是加入input()阻止程序退出了。

**Comment by Erohal** [comment]
Using a while true condition will be a batter solution
